/**
 * @file gui.h
 * @brief GUI application header
 * @date 01-29-2025
 */
#ifndef GUI_H
#define GUI_H

#define MAX_NUM_PAGES 2u
#define MAX_NUM_DATA_COL 2u // 2 data columns, raw and pv

#define TAB_PAGE_0 0
#define TAB_PAGE_1 1u
#define MAX_NUM_CH_PER_PAGE 8u

#include "imain-window.h" // Exposes the IMainWindow interface for all to see

#define MAX_FONT_SIZE 32
#define DEFAULT_DATA_DISP_FONT_FAMILY "LiberationMono"
#define DEFAULT_DATA_DISP_FONT_SIZE 10
#define DEFAULT_DATA_DISP_FONT_WEIGHT PANGO_WEIGHT_NORMAL
#define DEFAULT_LABEL_CH "Channel"
#define DEFAULT_LABEL_TAB0 "Ch 0-7"
#define DEFAULT_LABEL_TAB1 "Ch 8-15"

#define DEFAULT_NO_ALARM_BG_DCOLOR_R  (double)1.0  // white
#define DEFAULT_NO_ALARM_BG_DCOLOR_G  (double)1.0
#define DEFAULT_NO_ALARM_BG_DCOLOR_B  (double)1.0
#define DEFAULT_HI_ALARM_BG_DCOLOR_R  (double)0.82 // red
#define DEFAULT_HI_ALARM_BG_DCOLOR_G  (double)0.0
#define DEFAULT_HI_ALARM_BG_DCOLOR_B  (double)0.0
#define DEFAULT_MID_ALARM_BG_DCOLOR_R (double)1.0 // orange
#define DEFAULT_MID_ALARM_BG_DCOLOR_G (double)0.7
#define DEFAULT_MID_ALARM_BG_DCOLOR_B (double)0.0
#define DEFAULT_LO_ALARM_BG_DCOLOR_R  (double)0.9  // yellow
#define DEFAULT_LO_ALARM_BG_DCOLOR_G  (double)0.9
#define DEFAULT_LO_ALARM_BG_DCOLOR_B  (double)0.0
#define DEFAULT_FLT_ALARM_BG_DCOLOR_R (double)0.82 // red
#define DEFAULT_FLT_ALARM_BG_DCOLOR_G (double)0.0
#define DEFAULT_FLT_ALARM_BG_DCOLOR_B (double)0.0

#define DEFAULT_NO_ALARM_BG_COLOR16_R  (guint16)(DEFAULT_NO_ALARM_BG_DCOLOR_R*65535)
#define DEFAULT_NO_ALARM_BG_COLOR16_G  (guint16)(DEFAULT_NO_ALARM_BG_DCOLOR_G*65535)
#define DEFAULT_NO_ALARM_BG_COLOR16_B  (guint16)(DEFAULT_NO_ALARM_BG_DCOLOR_B*65535)
#define DEFAULT_HI_ALARM_BG_COLOR16_R  (guint16)(DEFAULT_HI_ALARM_BG_DCOLOR_R*65535)
#define DEFAULT_HI_ALARM_BG_COLOR16_G  (guint16)(DEFAULT_HI_ALARM_BG_DCOLOR_G*65535)
#define DEFAULT_HI_ALARM_BG_COLOR16_B  (guint16)(DEFAULT_HI_ALARM_BG_DCOLOR_B*65535)
#define DEFAULT_MID_ALARM_BG_COLOR16_R (guint16)(DEFAULT_MID_ALARM_BG_DCOLOR_R*65535)
#define DEFAULT_MID_ALARM_BG_COLOR16_G (guint16)(DEFAULT_MID_ALARM_BG_DCOLOR_G*65535)
#define DEFAULT_MID_ALARM_BG_COLOR16_B (guint16)(DEFAULT_MID_ALARM_BG_DCOLOR_B*65535)
#define DEFAULT_LO_ALARM_BG_COLOR16_R  (guint16)(DEFAULT_LO_ALARM_BG_DCOLOR_R*65535)
#define DEFAULT_LO_ALARM_BG_COLOR16_G  (guint16)(DEFAULT_LO_ALARM_BG_DCOLOR_G*65535)
#define DEFAULT_LO_ALARM_BG_COLOR16_B  (guint16)(DEFAULT_LO_ALARM_BG_DCOLOR_B*65535)
#define DEFAULT_FLT_ALARM_BG_COLOR16_R (guint16)(DEFAULT_FLT_ALARM_BG_DCOLOR_R*65535)
#define DEFAULT_FLT_ALARM_BG_COLOR16_G (guint16)(DEFAULT_FLT_ALARM_BG_DCOLOR_G*65535)
#define DEFAULT_FLT_ALARM_BG_COLOR16_B (guint16)(DEFAULT_FLT_ALARM_BG_DCOLOR_B*65535)


#define DEFAULT_NO_ALARM_FG_DCOLOR_R  (double)0.0  // black
#define DEFAULT_NO_ALARM_FG_DCOLOR_G  (double)0.0
#define DEFAULT_NO_ALARM_FG_DCOLOR_B  (double)0.0
#define DEFAULT_HI_ALARM_FG_DCOLOR_R  (double)1.0 // white
#define DEFAULT_HI_ALARM_FG_DCOLOR_G  (double)1.0
#define DEFAULT_HI_ALARM_FG_DCOLOR_B  (double)1.0
#define DEFAULT_MID_ALARM_FG_DCOLOR_R (double)0.0 // black
#define DEFAULT_MID_ALARM_FG_DCOLOR_G (double)0.0
#define DEFAULT_MID_ALARM_FG_DCOLOR_B (double)0.0
#define DEFAULT_LO_ALARM_FG_DCOLOR_R  (double)0.0  // black
#define DEFAULT_LO_ALARM_FG_DCOLOR_G  (double)0.0
#define DEFAULT_LO_ALARM_FG_DCOLOR_B  (double)0.0
#define DEFAULT_FLT_ALARM_FG_DCOLOR_R (double)0.0 // black
#define DEFAULT_FLT_ALARM_FG_DCOLOR_G (double)0.0
#define DEFAULT_FLT_ALARM_FG_DCOLOR_B (double)0.0
#define DEFAULT_NO_ALARM_FG_COLOR16_R  (guint16)(DEFAULT_NO_ALARM_FG_DCOLOR_R*65535)
#define DEFAULT_NO_ALARM_FG_COLOR16_G  (guint16)(DEFAULT_NO_ALARM_FG_DCOLOR_G*65535)
#define DEFAULT_NO_ALARM_FG_COLOR16_B  (guint16)(DEFAULT_NO_ALARM_FG_DCOLOR_B*65535)
#define DEFAULT_HI_ALARM_FG_COLOR16_R  (guint16)(DEFAULT_HI_ALARM_FG_DCOLOR_R*65535)
#define DEFAULT_HI_ALARM_FG_COLOR16_G  (guint16)(DEFAULT_HI_ALARM_FG_DCOLOR_G*65535)
#define DEFAULT_HI_ALARM_FG_COLOR16_B  (guint16)(DEFAULT_HI_ALARM_FG_DCOLOR_B*65535)
#define DEFAULT_MID_ALARM_FG_COLOR16_R (guint16)(DEFAULT_MID_ALARM_FG_DCOLOR_R*65535)
#define DEFAULT_MID_ALARM_FG_COLOR16_G (guint16)(DEFAULT_MID_ALARM_FG_DCOLOR_G*65535)
#define DEFAULT_MID_ALARM_FG_COLOR16_B (guint16)(DEFAULT_MID_ALARM_FG_DCOLOR_B*65535)
#define DEFAULT_LO_ALARM_FG_COLOR16_R  (guint16)(DEFAULT_LO_ALARM_FG_DCOLOR_R*65535)
#define DEFAULT_LO_ALARM_FG_COLOR16_G  (guint16)(DEFAULT_LO_ALARM_FG_DCOLOR_G*65535)
#define DEFAULT_LO_ALARM_FG_COLOR16_B  (guint16)(DEFAULT_LO_ALARM_FG_DCOLOR_B*65535)
#define DEFAULT_FLT_ALARM_FG_COLOR16_R (guint16)(DEFAULT_FLT_ALARM_FG_DCOLOR_R*65535)
#define DEFAULT_FLT_ALARM_FG_COLOR16_G (guint16)(DEFAULT_FLT_ALARM_FG_DCOLOR_G*65535)
#define DEFAULT_FLT_ALARM_FG_COLOR16_B (guint16)(DEFAULT_FLT_ALARM_FG_DCOLOR_B*65535)


int run_gui_application(int argc, char *argv[]);

#endif // GUI_H
